### ISSUE TITLE
入門受付メール文面

### ISSUE THREAD

**Issue by igaiga** [terakoya/rails-management#1]
参加される方へ送るメールの文面

---

Rails寺子屋師範の五十嵐です。
このたびは参加申込みをいただきありがとうございました。
寺子屋への入門を受け付けましたので、
以下にお目通しいただきますようお願い致します。
当日お会いできるのを師範一同、楽しみにしております。

■概要
日時: 2013 年 3 月 23 日（土）10:00 - 17:00 （受付 9:30 - 10:00）
場所: 株式会社オプティム 東京都港区港南1丁目6−34 品川イースト1階 (受付)
Google Maps: http://g.co/maps/t382x
公式ページ: http://rails.terakoya.io/
（連絡事項がある場合は、今後も、公式ページへ掲載していきます。）
懇親会のお知らせ: 本会終了後に懇親会(軽食付き)を計画しております。
当日会場にて参加受付を行いますので、ぜひご参加ください。

■ 注意事項
10:00 の開始時刻に遅れる場合は、本メール最下部の問い合わせ先までご連絡をお願いします。
無線 LAN をご利用いただけます。設定方法は当日説明いたします。
電源タップを用意しています。ただし、数に限りがございますので譲り合ってご使用ください。

■当日の持ち物
・お弁当（お昼ご飯を会場でみんなで食べましょう。会場近くにコンビニもあります。）
・Mac/PC

■Rails環境のインストール
たとえば以下のページを参考に、Rails環境のインストールを事前に行うと
当日はスムースに進めることができます。
http://railsgirls-jp.github.com/install/

分からない方、エラーなどでうまくインストールできない場合は、
無理せず当日にご相談ください。
当日の午前中はインストールの時間に宛てていますのでその時間で対応いたします。
インストールが完了している方々へはエクストラで何かできる時間にする予定です。

■華組の方へ
申込み時に「華組」で希望を出した方は、
当日に取り組みたい課題を考えておいてください。
（師範から提供する課題はありません。
　各自で課題を設定して進める形式を予定しております。）

■Windows環境の方へ
会場のネットワーク帯域の都合、および当日の時間の有効活用のため、
事前にWindowsUpdateを完了させておいてください。

ご不明な点がありましたら以下までご連絡ください。
連絡先: igaiga@gmail.com

**Comment by RooandQoo** [comment]
LGTM :sushi: (言ってみたかった

**Comment by igaiga** [comment]
- （有線 LAN はご利用いただけません。）

**Comment by igaiga** [comment]
■華組の方へ
申込み時に「華組」で希望を出した方は、
当日に取り組みたい課題を考えておいてください。
（師範から提供する課題はありません。
　各自で課題を設定し、質問がある場合は師範が対応して進める形式を予定しております。）

**Comment by igaiga** [comment]
案2
■華組の方へ
申込み時に「華組」で希望を出した方は、
当日に取り組みたい課題を考えておいてください。
（各自で課題を設定し自主的に進める形式を予定しております。
　師範が席を離れている場合もありますが、
　質問はいつでも受け付けますので、気軽に声をかけてください。）

**Comment by igaiga** [comment]
## 送信版

Rails寺子屋師範の五十嵐です。
このたびは参加申込みをいただきありがとうございました。
寺子屋への入門を受け付けましたので、
以下にお目通しいただきますようお願い致します。
当日お会いできるのを師範一同、楽しみにしております。

■概要
日時: 2013 年 3 月 23 日（土）10:00 - 17:00 （受付 9:30 - 10:00）
場所: 株式会社オプティム 東京都港区港南1丁目6−34 品川イースト1階 (受付)
Google Maps: http://g.co/maps/t382x
公式ページ: http://rails.terakoya.io/
（連絡事項がある場合は、今後も、公式ページへ掲載していきます。）
懇親会のお知らせ: 本会終了後に懇親会(軽食付き)を計画しております。
当日会場にて参加受付を行いますので、ぜひご参加ください。

■ 注意事項
10:00 の開始時刻に遅れる場合は、本メール最下部の問い合わせ先までご連絡をお願いします。
無線 LAN をご利用いただけます。設定方法は当日説明いたします。
（有線 LAN はご利用いただけません。）
電源タップを用意しています。ただし、数に限りがございますので譲り合ってご使用ください。

■当日の持ち物
・お弁当（お昼ご飯を会場でみんなで食べましょう。会場近くにコンビニもあります。）
・Mac/PC

■Rails環境のインストール
たとえば以下のページを参考に、Rails環境のインストールを事前に行うと
当日はスムースに進めることができます。
http://railsgirls-jp.github.com/install/

分からない方、エラーなどでうまくインストールできない場合は、
無理せず当日にご相談ください。
当日の午前中はインストールの時間に宛てていますのでその時間で対応いたします。
インストールが完了している方々へはエクストラで何かできる時間にする予定です。

■華組の方へ
申込み時に「華組」で希望を出した方は、
当日に取り組みたい課題を考えておいてください。
（各自で課題を設定し自主的に進める形式を予定しております。
　師範が席を離れている場合もありますが、
　質問はいつでも受け付けますので、気軽に声をかけてください。）

■Windows環境の方へ
会場のネットワーク帯域の都合、および当日の時間の有効活用のため、
事前にWindowsUpdateを完了させておいてください。

ご不明な点がありましたら以下までご連絡ください。
連絡先: igaiga じーめーる

**Comment by june29** [comment]
これ Close してよいのでは？状況を把握している人がいたら、適切に処理していただきたく！

**Comment by asonas** [comment]
メール送り済みなので Close にします！
