### ISSUE TITLE
facebookページを考えたい

### ISSUE THREAD

**Issue by igaiga** [terakoya/rails-management#13]
要件
・宣伝用にfbページをつくりたい
・参加した方のアフターフォローをしたい

現在クローズドなアフターフォローグループがあるが、これの再編も視野にいれて考えたい。

**Comment by igaiga** [comment]
facebookに詳しい方、ご提案いただけると嬉しい〜。

**Comment by june29** [comment]
ぼくなりの思考整理メモです。発案者である @igaiga さんの反応を見たい！
- 宣伝のチャンネルを増やしたい？
  - 現状は「各師範の個人チャンネル」「高専カンファレンスのチャンネル」くらいかな？
  - そこに「Facebook Page」なり「Twitter アカウント」なりを増やしたい？
- 参加した方のアフターフォローってなんだろう？
  - どういったシナリオを想定している？
  - 現状の「できていること」と「できていないこと」はなあに？
  - たとえばぼくは、過去の参加者のブログのいくつかは購読していて、その内容についてやりとりしていたり

**Comment by igaiga** [comment]
宣伝のチャンネルを増やしたい？はその通りで、先日高専機構に行った時に先生がfb使う人が多いとのことだったので、そこにリーチしたいので作りたいという動機です。あと、説明が楽になる。

参加した方のアフターフォローは、参加者さんが継続して質問とか相談できる場所を用意したいのが要件。

現状できていることはなんだろう？fbページ作ったけど、あんまり発言もないので私の観測範囲だとうまく機能してない気もする。じゅーんさんらが個人的にフォローしてくれてるなら、それはそれで解決してるのでとても良い。そしたらフォロー用fbグループは不要なのかもしれない。あと、前回fbグループへ誘導忘れた気がする。(ごめんなさいごめんなさい)
ってことで、参加してくれた人のアフターフォローは現状がよくわからん、がスタートラインかなー。

**Comment by june29** [comment]
> 先日高専機構に行った時に先生がfb使う人が多いとのことだったので、そこにリーチしたいので作りたいという動機です。あと、説明が楽になる。

なるほど〜！明確な理由があったのですね。

アフターフォローについては、何が誰にとってうれしいのかをもうちょっと考えたいなぁ。「参加者さんは、イベント後になにか質問したいの？」ってのも、今のぼくにはよくわかっていないのでした。わかっている人がいるなら教えてほしい！現状をもう少し把握しないと「Group が Page に変わっただけで、特に何も起こらない」ってことにもなりかねないかな、と。

日本の RailsGirls なんかは、参加者さんがイベント後にやりたいことと、それに対する受け皿があって上手にまわっているように見えます。ぼくより詳しいであろう @igaiga さんから見てどうだろう、RailsGirls のいいエッセンスを terakoya の方にも持ってこれそうだったりしますかねぇ。

アフターフォローについては別スレにして、高専の先生にリーチするために Facebook Page をつくるってことにして進めちゃってもいい気がします！

**Comment by igaiga** [comment]
高専の先生にリーチする目的を前提としたときに、facebookの「グループ（public）」と「ページ」のどっちを作ったらいいかな？「ページ」はいいね！できて気軽な印象。「グループ」はjoinするのは「いいね！」よりもちょっと敷居高いかもだけど、参加者のブログとかを参加者さん自身が書いてくれたりしてると雰囲気が伝わっていいかも。私は「グループ(public)」がいいかなと思ってるんだけど、みなさんいかがですか？（facebookに詳しいお客様〜）

アフターフォローは解決（改善）が難しい問題ですね。RailsGilrsは1回だけしか参加できないって性質もあり、開催後も毎月1回RailsGilrsMore!をやっていてうまく回ってる感じです。Rails寺子屋は東京以外の人も多いので毎月は難しいけど、何回でも参加して良いものなので、今くらいのペースでリピーターさんがいる状態ならRailsGilrs相当なんだろうなと思ってます。

じゅーんさんの書いてる「過去の参加者のブログのいくつかは購読していて、その内容についてやりとりしていたり」のような、師範と参加者が野良につながってる仕組みが作れたらそれが理想なのかもしれないね。
（ @june29 さんいろいろ提案くれてありがとう！）

**Comment by june29** [comment]
「リーチ」が目的なら Page に1票ですね。どちらかというと単方向の「発信」の使い方かなぁ、と。運営に使っているように双方向のやりとりがしたいなら Group だと捉えています。

現状の雰囲気からすると、寺子屋の参加者さんにぼくらのために何か発信してもらうのはむつかしい気もする。それよりは、そもそもの目的である「リーチしたい」を素直に目指して、割り切って「発信用の Page をつくる」として、ぼくらが参加者さんのブログ記事なんかを見つけたらその Page から発信していく、というのがいいと思います。

けっこう感覚的なところもあるので、明確な根拠を示せておらず申し訳ありませんが、ぼくの意見はそんな感じです！

**Comment by ryopeko** [comment]
いがさんが作ってくれましたー 
https://www.facebook.com/rails.terakoya

**Comment by igaiga** [comment]
これから育てていくということで、ここはひとまずクローズ。
