### ISSUE TITLE
参加者の事前交流チャンネルを用意する

### ISSUE THREAD

**Issue by june29** [terakoya/rails-management#2]
特に遠方からの参加者のみなさんは、移動や宿泊に関する情報を交換できるとうれしいと思いますので、用意することにしました。

**Comment by june29** [comment]
Facebook の Secret Group を作成しました。Secret Group にしたのは、すべての参加者について「自身の Facebook アカウントを明かされてもよいか」を確認できていないからです。安全側に倒す判断です。

**Comment by june29** [comment]
参加者のみなさんに送るメールの文章をつくりました。レビューお願いします！

---

Subject: 【Rails寺子屋】事前交流スペースを用意しました！

Body:
Rails寺子屋 参加予定者のみなさん

師範の、じゅーんと申します。こんにちわ！
今回のイベントでは、どうぞよろしくお願いします。

参加者のみなさん同士で事前に交流できるスペースを用意したのでお知らせします！
Facebook の Secret Group として作成しました。

特に、遠方からご来場のみなさんは、移動や宿泊について考えることも多いかと思います。
約1ヶ月後の当日に向けて、旅程を共有するなど、ご活用いただけるとうれしいです！

この Group には、ぼくたち師範も参加していますので、
もし今の時点から不安に感じることなどあれば、ここで質問していただいても構いません。

Group への参加は任意です。参加を希望される方は、
- あなたの Facebook のプロフィールページの URL

を添えて、ぼくのこのメールにご返信くださいませ！

以上、よろしくお願いします！

**Comment by igaiga** [comment]
良いと思います！気になるとすると.,インバイト作業はじゅーんさん1人になっちゃうけど大丈夫かな？

あと、これは書かなくて良い情報ですが、この部屋を開催後も交流に使って欲しいなと思ってます。：）

**Comment by june29** [comment]
> インバイト作業はじゅーんさん1人になっちゃう

たしかにそうですねぇ。負荷的にはぜんぜん問題ないと思っていて、あとは対応漏れがないように気を付けるだけです…！
対外的なメールアドレスがひとつあれば解決するお話ではある。それを用意するかどうか、ってところですかね。

**Comment by igaiga** [comment]
このためだけに公開アドレス作るのはめんどいから、じゅーんさんが大変でなければこのまま行くのでどでしょ？
(もしくはボランティア隊をCCに入れて送信して、全員返信してもらうって手も考えたけど、煩雑なので)

**Comment by june29** [comment]
Secret Group じゃなくて Private Group にすれば「参加したい」って操作をしてもらうだけで楽だから、
そっちに寄せることも検討してみたのですが…！

Private Group だと外から参加者が見えちゃうし、今回は若い子(未成年を含む)が多いこともあって、
あんまり彼ら彼女らの情報を整理された状態で置いておくのは乗り気じゃないのでした。

「Reply to all」をお願いしても忘れられたら漏れる、かつ、しばしば忘れられる、ので、効果薄いですかね。

このまま良案が出てこなければ、今回はぼくが引き受けるってことにしようかと思います :ok_woman:

**Comment by june29** [comment]
メールを送信しました！あとは、お返事を待って、ひとつずつ対応していきます。

**Comment by asonas** [comment]
:+1:

**Comment by june29** [comment]
「用意する」は完了したので Close します！
