### ISSUE TITLE
【第4回】ペアプロ

### ISSUE THREAD

**Issue by sorah** [terakoya/rails-management#23]
## テーマ

http://rosylilly.hatenablog.com/entry/2013/10/21/190019

これだけだと association 0 なので、コメント機能くらいつけようかと思う。
## すすめかた
- Rails 4.1.1
- ERB
- 最低限の gem
  - rspec, timecop, factory_girl
- controller, model spec のみ
## todo
- [ ] 正常系、異常系仕様リストアップ
- [ ] rspec の example リストに落とす
- [ ] 担当箇所振り分け
- [ ] 万が一の時の完成形テストの作成
## そのた
- [ ] send_file のテスト書き方周り

**Comment by sorah** [comment]
#17

**Comment by sorah** [comment]
@asonas 今日のはなしをベースに更新した

**Comment by asonas** [comment]
https://github.com/terakoya/kura
当日使うリポジトリ

**Comment by igaiga** [comment]
（いまさら）第4回無事に終わったのでクローズ。今回も好評でしたありがとう！！＞そらはさん
