### ISSUE TITLE
【第4回】一橋講義出張所

### ISSUE THREAD

**Issue by machu** [terakoya/rails-management#24]
一橋講義出張所ですが、「RailsGirlsの次」として、以下の3つをやるくらいですかね。
- 第20回 2013.10.31 CRUD基礎
- 第21回 2013.11.14 new, create
- 第22回 2013.11.28 model

はじめてRailsをやるときに、暗黙の規約がよく分からない！で躓くので、この資料でカバーできればなと思います。

資料一覧はこちらから
https://github.com/igaiga/hitotsubashi-ruby-2013

**Comment by igaiga** [comment]
そうですね、そんな感じで考えてました。まちゅさんのRuby編をやってもいいのかなと考えてますがどうですか？（他の言語はやってるけどRubyは初めてって人も多そうなので）
午前：Ruby講座＋一番小さなRailsApp(第18回)
午後：CRUD基礎、new, create, model
とか。

**Comment by machu** [comment]
なるほど。Rails寺子屋なのでRailsと思ってしまいました。RailsGirlsの次ステップとして、Ruby基礎とRails基礎の2つあってもいいですね。当日の参加者状況でレベル決めましょう。
もしRuby講義やるなら、午前に小さなRailsまでやるとお腹いっぱいになりそうです。小さなRailsのとこはRailsGirlsでカバーできるかもと思ってますが、これまでの経験でどうでしょう？

**Comment by igaiga** [comment]
小さなRailsは、まちゅさんの言う通りカバーできてると思うので、時間余ったらのオプショナルでいいと思います。Ruby講座をメインにして、そちらで設計しましょう。
まちゅさんも言ってる通り、蓋を開けてみないと分からないところが多いので、また明日やりながら相談しましょう〜。

**Comment by igaiga** [comment]
午前は時間が余ったらsinatraで遊ぶでもいいかもしれない。

**Comment by machu** [comment]
:+1:

**Comment by igaiga** [comment]
（いまさら）第4回無事に終わったのでクローズ (´▽`)
