### ISSUE TITLE
当日必要な物品

### ISSUE THREAD

**Issue by igaiga** [terakoya/rails-management#3]
買う
- スケッチブック x テーブル数(6: 華, asonas, rq, iga, mrkn, nishijima)

用意する
- 名簿
- Railsインストーラを入れた USB メモリ

あやちゃん or オプティムさんに借りたい
- 名札入れ
- 名札用紙
- ペン（受付用、スケッチブック用）

参考
- スケッチブック（約A4、かっこいいやつ、asonasさんご推薦）  @782円
- http://www.amazon.co.jp/dp/B001A1TNW4
- スケッチブック（約A3）x 6：@591円
- http://www.amazon.co.jp/dp/B000IGX9QS/

**Comment by asonas** [comment]
マイクがあるとよさそうですねー。
オプティムさんで借りれるかしら

**Comment by asonas** [comment]
あと、当日のBGM用にスピーカーを持参します

**Comment by igaiga** [comment]
スピーカーいいね！:+1:
全体で話す機会は少ないけど、もしマイクあったら嬉しい感じだね。：）

**Comment by igaiga** [comment]
これでうまくまわりましたね。：）
close.
