### ISSUE TITLE
ワークショップで使うRailsとRubyのバージョンを決める

### ISSUE THREAD

**Issue by igaiga** [terakoya/rails-management#7]
Railsは4.0.x（最新）、RubyはRailsInstallerで入るもの(1.9.3)、とかかな。
HerokuがRails4.0対応してればこれで良さそう。

**Comment by igaiga** [comment]
ご意見ください。

**Comment by june29** [comment]
基本は Rails 4 系に賛成で、ただ自分が Rails 4 系で (今のところ) ちゃんとアプリをつくってデプロイするところまでの素振りをこなせていないので、ちょっと弱気。という気持ちだけ表明しておきます。

**Comment by mitaku** [comment]
Rails4.0で賛成です。

HerokuはRails4対応していますが、RailsGirlsのマテリアルそのままだとうまくいかないですね。（きっと、おそらく）

```
gem 'rails_12factor', group: :production
```

こんなことしないといけないと思います。（未確認）

https://devcenter.heroku.com/articles/rails4-getting-started

**Comment by mrkn** [comment]
Rails は 4.0 で、Ruby は 1.9.3 と 2.0.0 のどちらかインストール可能な方を選びましょう。

**Comment by mrkn** [comment]
> HerokuはRails4対応していますが、RailsGirlsのマテリアルそのままだとうまくいかないですね。（きっと、おそらく）

日本語版のマテリアルは対応させました。

http://railsgirls.jp/heroku/

**Comment by igaiga** [comment]
みなさんご意見ありがとうございます！mrknさんの書いてる
Railsは4.0, Rubyは1.9.3or2.0.0
で良さそうですね。：）

RailsGirlsのマテリアル、/app ページと /install ページも対応と動作確認したいですね。(私も週末にwinで動作確認しようかと思ってます)

**Comment by igaiga** [comment]
june30さんの不安の件(こういうの歓迎ですよー)は、周りの慣れてる師範に頼る、とかですかねー。

**Comment by igaiga** [comment]
RailsGirlsの資料(/app)がRails4で動くか確認しました。Windows8環境のRailsInstaller+gem update rails で問題なく動きました。資料はRailsGirlsの経路で更新しておきます。（そんなに変更なかった。変更箇所は以下。）

■/install ページ
gem update rails --no-ri --no-rdoc

■/app ページ
rails3
<%= stylesheet_link_tag "application", media: "all" %>
rails4
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

rails3
rm public/index.html
rails4
不要

**Comment by igaiga** [comment]
ってことで、不安もなくなったので
Rails：4.0
Ruby：1.9.3or2.0.0
で決定にします〜。

**Comment by igaiga** [comment]
あ、june30さんの不安の件は「他の師範を頼る」以外で何か必要だったらReopenしてください。（勢いで閉じちゃった。ごめん。）
